(function ($) {
  Drupal.behaviors.capping_liberty = {
    attach: function(context, settings) {

      var label_mappings = [
{ label:"Case Group 10C", "text":"In the eighteenth century, the heraldic eagle, often with two heads, appeared on coins as the symbol of both the Holy Roman Empire and the Russian Empire."},
{ label:"Case Group 10D", "text":"The eagle made its first appearance on American coinage on the cents of Massachusetts under the Confederation; its appearance was copied from the Great Seal."},
{ label:"European Precedents", "text":"<p>Despite protests about British policies that kept specie from circulating in the American colonies, the coinage of Great Britain was the basis of the pre-Revolutionary monetary system. Its obverse depiction of the king was clearly inappropriate for the new republican coinage, but did suggest the basic image of a portrait bust as the most familiar obverse; the reverse depiction of Britannia on the halfpenny, the denomination most widely in circulation in the colonies, established the precedent for a human personification of an abstract concept.</p><p>The silver coinage in common circulation in the colonies was the Spanish piece of eight, known as the Spanish dollar for its monetary equivalence to coinages on the German thaler standard. This coin became less appropriate as a model for the North American coinage after 1772, when the symbolic (though expressly imperial) pillars of Hercules gave way to the monarch&rsquo;s portrait as the obverse image.</p><p>In other monarchies, the image of the ruler also dominated the obverse of coins. The importance accorded this portrait resulted in its presence on the coinage of the first years of the Revolutionary government; as late as 1793, Louis XVI appeared on the obverse of French coins whose reverse proclaimed Year 5 of Liberty. Among the few non-monarchical minters&mdash;the Netherlands, Venice, the Swiss cantons, and the free imperial cities of the Holy Roman Empire&mdash;only the Netherlands offered appropriate numismatic imagery for the American Republic.</p>"},
{ label:"Colonial Money", "text":"<p>Only one coinage had been minted in the American colonies: the series of seventeenth-century silver issues of the Massachusetts Bay Colony. Most of these bear the date 1652 (when the British throne was vacant during the Civil War), but were actually minted intermittently in succeeding decades. Various privately minted tokens, some bearing references to America, were produced under royal patent and imported into the colonies in the eighteenth century to make up for the shortage of official British coins. In 1773 the colony of Virginia pressed its claim, based on its 1609 charter, to a right for its own coinage, for which the Tower Mint in London supplied a small issue.</p><p>As a monetary expedient, each American colony issued its own paper money&mdash;among the earliest of world banknotes&mdash;denominated in British pounds or Spanish dollars. These notes usually bore imagery related to the individual colony, but some included versions of the image of Britannia that appeared on the royal coinage.</p>"},
{ label:"Case Group 1C", "text":"&nbsp;"},
{ label:"Case Group AA", "text":"<p>United States, Continental Congress. An Ordinance for the Establishment of the Mint of the United States of America; and for Regulating the Value and Alloy of Coin.</p>"},
{ label:"Case Group 4A", "text":"Several American mints that produced imitative English halfpennies have been identified, either with the name of a minter or, as in this case, an allusion to the place of their origin."},
{ label:"Case Group 4B", "text":"<p>This proposal for a national coin, of unexpressed value, is known in silver, copper, brass, and tin examples from a few die combinations. It was produced by Elisha Gallaudet (ca. 1730&ndash;1779), an engraver in Freehold, New Jersey, who made the cuts for the paper currency bearing these same motifs based on drawings by Benjamin Franklin.</p>"},
{ label:"Case Group 4C", "text":"<p>At the very beginning of the Revolutionary period, Paul Revere (1734&ndash;1818) printed a banknote for Massachusetts with patently political content. Georgia, North Carolina, South Carolina, and Virginia also produced notes with patriotic themes, but the banknotes issued by other states and by the Continental Congress were mainly neutral in iconography</p>"},
{ label:"Case Group 4D", "text":"These pieces were produced in England on the initiative of Gouverneur Morris (1752&ndash;1816), Assistant Superintendent of Finance of the Continental Congress. They are known from many dies and in various states of wear, so probably saw circulation in America as a halfpenny. The image of a new constellation of stars follows that in use on American flags for the preceding decade."},
{ label:"Case Group 4E", "text":"<p>The first issue of independent coinage under the Articles of Confederation appeared in 1785, by Vermont, which had broken away from New York and Massachusetts but was not yet recognized as a state. Its earliest issues were innovative in appearance, but they changed in 1786 to an imitation of British issues. Connecticut also began its coinage in 1785, with English types and a halfpenny denomination, and continued it through 1788. New Jersey&rsquo;s coppers, struck by a number of private mints from 1786 through 1788, bore distinctive types: a local agricultural emblem for the obverse and the newly proposed national seal and motto for the reverse. Massachusetts also chose distinctive types&mdash;an Indian obverse and eagle reverse&mdash;and issued both a cent and a half cent denomination in 1787 and 1788. New York&rsquo;s legislature never approved a state coinage, but several private entrepreneurs struck proposals for its consideration.</p>"},
{ label:"Case Group 4F", "text":"<p>Although the ordinance of 1786 called for the establishment of a mint, the only national coinage actually issued under the Articles of Confederation was a copper cent produced on contract by a private minter. It copied, with minor changes, the 1775 proposal by Benjamin Franklin that had been used on paper money and the &ldquo;continental dollar patterns&rdquo; of 1776.</p>"},
{ label:"Case Group 5A", "text":"&nbsp;"},
{ label:"Case Group 5B", "text":"<p>While Congress debated the imagery for the new national coinage, minters in both England and America produced patterns on the assumption that Washington&rsquo;s portrait would be used. Even after the concept of a presidential coinage was rejected, token manufacturers continued to mint pieces with Washington&rsquo;s image, sometimes apparently with the intention of circulating them in America.</p>"},
{ label:"Case Group 6A", "text":"<p>The egg-shaped pileus hat of the Dioscuri is visible on the coins of Hellenistic Bactria (modern-day Afghanistan) from the second century BCE.</p>"},
{ label:"Case Group 6B", "text":"<p>The temple dedicated to Jupiter and Libertas, shown on #3, had cult statues of both deities in equal proportion. On the other coins, Libertas is displayed with the pileus or vindicta or identified by name. Though the magistrates identified on the earlier coins are not the Cassius who assassinated Caesar, the family had a long commitment to anti-tyrannical causes, and the exact identification and chronology of these coins had not been established in the eighteenth century.</p>"},
{ label:"Case Group 6C", "text":"<p>On the coinage of the Roman Empire, Liberty was depicted standing, holding her pileus to one side and, usually, the vindicta to the other.</p>"},
{ label:"Case Group 6D", "text":"<p>Dutch coins bearing the cap on a staff circulated in the American colonies before the Revolution.</p>"},
{ label:"Case Group 8A", "text":"<p>Plate II of the 1842 Manual by Eckfeldt and Du Bois illustrates most of the types of United States silver coins of their day. On these, the obverse representation of Liberty goes from being a portrait of a woman with flowing hair, to being one with hair tied back neatly, to a female head in a hat derived from the Phyrgian cap, to a seated figure holding the vindicta and pileus. The eagle starts naturalistic, becomes heraldic, and then appears as a combination of the two.</p>"},
{ label:"Case Group 9A", "text":"<p>The die study by Maris has allowed subsequent numismatists to group the issues together, compare the letter punches used on other issues, and assign specimens 1, 2, and 3 to the mint operated in Morristown by Walter Mould, and 4 and 5 to the mint operated by Thomas Goadsby in Rahway.</p>"},
{ label:"Case Group 10A", "text":"<p>The eagle perched on a lightning bolt, depicted on the obverse of this coin, was a symbol of Zeus. The dimple that appears in the center of both faces on all large Ptolemaic bronzes of this period has defied consistent explanation.</p>"},
{ label:"Case Group 10B", "text":"<p>The eagle appears on the coins of both the opponents of Caesar and his successor, Octavian, probably as a sign of the loyalty of the army.</p>"},
{ label:"Case Group 11A", "text":"<p>The half disme (the use of the Old French spelling is traditional for this coin) is the only official issue struck under the Mint Act of 1792 to bear that date. It is believed to have been produced in the basement of a private home in Philadelphia, using bullion supplied by George Washington. The figure of Liberty, believed to have been inspired by Martha Washington, has free-flowing hair but no other identifying attributes. The Cass specimen was purchased in the auction held by Thomas Elder on April 27, 1917, where it was identified as the finest known specimen.</p>"},
{ label:"Case Group 11B", "text":"<p>Because the striking of silver and gold coins had to await the acquisition of bullion, the first coins struck in the Mint were copper cents and half cents. The 1793 cents followed the half disme in presenting Liberty as a woman with freely flowing hair and no attributes. The pileus was added in 1794, but removed in 1796 in favor of a much more contemporary image of a draped bust of a woman, identifiable as Liberty only by the legend above her head.</p>"},
{ label:"Case Group 11C", "text":"<p>The half cent followed the Libertas Americana medal in facing Liberty to the left, but her cap resembles the Phrygian hat more than the true pileus. The half cent was minted with the attributes of Liberty through 1797; after a three-year hiatus in minting, the denomination was reintroduced with the draped bust of the other denominations.</p>"},
{ label:"Case Group 11D", "text":"<p>The minting of silver began in 1794 with dollars and half dollars. Liberty was portrayed as a woman with flowing hair and no identifying attributes. As on the copper coinage, the image was replaced with the more contemporary draped bust in 1795, a portrayal carried onto the quarter and dime when these were introduced the following year.</p>"},
{ label:"Case Group 11E", "text":"<p>On the gold coinage initiated in 1795, the female on the obverse does have a hat, an article somewhere between a pileus and a Phrygian cap, but it is perched on her head and bound up in a scarf in a manner with few precedents in ancient or European depictions of Liberty.</p>"},
{ label:"Case Group 2A", "text":"<p>Jean-Baptiste Nini (1717–1786). B. Franklin Américain, 1777. Three preparatory terra-cotta moulds and one cast medallion. Franklin’s image was spread through France on a series of terra-cotta medallions made by the Italian sculptor Jean-Baptiste Nini. The medallions were widely distributed in America as well. The three preparatory plasters on display here were shown at an exhibition at the Grolier Club in 1906 but have otherwise not been displayed or published.</p>"},
];
      
      /*Add your js code here*/
      $(document).ready(function() {
        $('.view-footer .view-content h3').each(function (i) {
          var label_code = $(this).text();
          var matching_display = _.find(label_mappings, function(mapping){ return mapping.label == label_code; });
          //console.log(matching_display);
          //console.log(test);
          //if(test == "Case Group 4A") {
            $(this).replaceWith("<div class='subcase-desc'>"+matching_display.text+"</div>");
          //}
        });
      });
    }
  }
})(jQuery);    
